CREATE DATABASE IF NOT EXISTS tasksdb

CREATE TABlE tasks (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(300),
  done BOOLEAN NOT NULL DEFAULT 0,
  createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABlE boardLists (
  idlist INTEGER PRIMARY KEY AUTO_INCREMENT,
  listtitle VARCHAR(200) NOT NULL,
  numtask INTEGER,
  createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABlE board (
  idboard INTEGER PRIMARY KEY AUTO_INCREMENT,
  boardtitle VARCHAR(200) NOT NULL,
  numlist INTEGER,
  createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



